management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  info:
    java:
      enabled: true
    os:
      enabled: true